services:
  mongodb:
    image: mongo:8.0

  mngrun:
    build: .
    environment:
      MONGO_URI: mongodb://mongodb:27017/dd
      GIT_SCRIPT_REPO: https://github.com/dhaanpaa-lab0/mngrun
    command: sleep infinity
    depends_on:
      - mongodb
